# Generated by Django 5.1.2 on 2024-10-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Physics", "Physics"),
                            ("Maths", "Maths"),
                            ("Chemistry", "Chemistry"),
                            ("Biology", "Biology"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        choices=[
                            (1, "Semester 1"),
                            (2, "Semester 2"),
                            (3, "Semester 3"),
                            (4, "Semester 4"),
                            (5, "Semester 5"),
                            (6, "Semester 6"),
                            (7, "Semester 7"),
                            (8, "Semester 8"),
                            (9, "Semester 9"),
                            (10, "Semester 10"),
                        ]
                    ),
                ),
                ("file", models.FileField(upload_to="study_materials/")),
            ],
        ),
    ]
